### ISSUE TITLE
App Compatibility Checklist

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Design-Patterns-Group-Assignment#10]
Is the App able to run in:
- [x] JDK 8
- [x] small laptop screen size
- [x] netbean IDE

**Comment by HowardYaw** [comment]
Element appear off in small laptop screen size
![image](https://user-images.githubusercontent.com/35193728/101329646-9c22f880-38ac-11eb-9a4e-2f2ecd3624aa.png)

**Comment by HowardYaw** [comment]
Fix laptop screen position issue on #11
