### ISSUE TITLE
Lantern is not render in the application

### ISSUE THREAD

**Issue by junzai97** [Five-Fishes/Design-Patterns-Group-Assignment#12]
Suspect the issue will occurs only if using Java SDK 8 but Java SDK 11.

**Comment by kachun333** [comment]
this fix works fine in my local. (using Intellij + JDK 11).
@HowardYaw @CarlosSia @LUXIANZE isit working for you guys? (what env you guys are using)

**Comment by HowardYaw** [comment]
Work for me as well in java8 and java11

**Comment by LUXIANZE** [comment]
Should we close this already?
